MATH: application.cpp File Reference
application.cpp File Reference
#include "expression.hpp"
#include <iostream>
#include <functional>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 10 of file application.cpp.
 {
     std::string input = "(-2)^2";
     Fraction t(lexify("a/b"));
     Fraction l(lexify("b/c"));
     std::cout << getStringFromTokens(t.divide(&l)->getTokens()) << std::endl;
     return 0;
 }
References Fraction::divide(), getStringFromTokens(), Factor::getTokens(), and lexify().