MATH: Expression Class Reference
Expression Class Reference
#include <expression.hpp>
Public Member Functions
Expression (std::vector< Token > _tokens)
Expression (Term *t)
Expression (Factor *f)
Expression (const Expression &e)
~Expression ()
std::vector< Token > getTokens ()
bool operator== (const Expression &e2)
bool operator!= (const Expression &e2)
void multiply (Factor *f)
void multiply (const Expression &e)
Data Fields
std::vector< Term * > terms
Private Member Functions
void organize (std::vector< Token > tokens)
Detailed Description
Definition at line 4 of file expression.hpp.
Constructor & Destructor Documentation
Expression() [1/4]
Expression::Expression (std::vector< Token > _tokens)
Definition at line 4 of file expression.cpp.
 {
     organize(_tokens);
 }
References organize().
Expression() [2/4]
Expression::Expression (Term * t)
Definition at line 9 of file expression.cpp.
 {
     terms.push_back(t);
 }
References terms.
Expression() [3/4]
Expression::Expression (Factor * f)
Definition at line 14 of file expression.cpp.
 {
     terms.push_back(new Term(f));
 }
References Term, and terms.
Expression() [4/4]
Expression::Expression (const Expression & e)
Definition at line 19 of file expression.cpp.
 {
     for (auto term : e.terms)
     {
         terms.push_back(new Term(*term));
     }
 }
References Term, and terms.
~Expression()
Expression::~Expression ()
Definition at line 27 of file expression.cpp.
 {
     for (auto term : terms)
         delete term;
 }
References terms.
Member Function Documentation
getTokens()
std::vector< Token > Expression::getTokens ()
Definition at line 33 of file expression.cpp.
 {
     std::vector<Token> returnVector;
     for (int i = 0; i < terms.size(); i++)
     {
         auto tempTokens = terms[i]->getTokens();
         if (i == 0 && tempTokens[0].value == "+")
             tempTokens.erase(tempTokens.begin());
         returnVector.insert(returnVector.end(), tempTokens.begin(), tempTokens.end());
     }
     return returnVector;
 }
References i, and terms.
Referenced by Fraction::getTokens(), Parenthesis::getTokens(), and Exponential::getTokens().
multiply() [1/2]
void Expression::multiply (const Expression & e)
Definition at line 81 of file expression.cpp.
 {
     Expression copy(*this);
     for (auto& term : terms)
     {
         delete term;
     }
     terms.clear();
     for (auto& eterm : e.terms)
     {
         for (auto& cterm : copy.terms)
         {
             Term* temp= new Term(*cterm);
             temp->multiply(*eterm);
             terms.push_back(temp);
         }
     }
 }
References Term::multiply(), Term, and terms.
multiply() [2/2]
void Expression::multiply (Factor * f)
Definition at line 73 of file expression.cpp.
 {
     for (auto& term : terms)
     {
         term->multiply(f);
     }
 }
References terms.
Referenced by Fraction::divide(), and Fraction::multiply().
operator!=()
bool Expression::operator!= (const Expression & e2)
Definition at line 68 of file expression.cpp.
 {
     return !(*this == e2);
 }
operator==()
bool Expression::operator== (const Expression & e2)
Definition at line 47 of file expression.cpp.
 {
     if (terms.size() != e2.terms.size())
         return false;
     // same as term, the expressions will be equal even if theyre out of order
     for (int i = 0; i < terms.size(); i++)
     {
         bool exists = false;
         for (int j = 0; j < terms.size(); j++)
         {
             if (*e2.terms[i] == *terms[j])
                 exists = true;
         }
         if (!exists)
             return false;
     }
     return true;
 }
References i, and terms.
organize()
void Expression::organize (std::vector< Token > tokens) private
Definition at line 102 of file expression.cpp.
 {
     // split the tokens into terms, skipping over each parenthesis
     int lastTermIndex = 0;
     int nextTermIndex = 0;
     for (int i = 0; i < tokens.size(); i++)
     {
         // skipping over parenthesis
         if (tokens[i].value == "(")
         {
             int nextParenthesisIndex = getParenthesisIndices(tokens, i).second;
             i = nextParenthesisIndex - 1;
         }
         else if ((tokens[i].value == "+" || tokens[i].value == "-") && i != 0)
         {
             nextTermIndex = i;
             std::vector<Token> termTokens;
             if (lastTermIndex == nextTermIndex)
             {
                 termTokens.clear();
                 termTokens.push_back(tokens[lastTermIndex]);
             }
             else
                 termTokens = std::vector<Token>(&tokens[lastTermIndex], &tokens[nextTermIndex]);
             terms.push_back(new Term(termTokens));
             lastTermIndex = nextTermIndex;
         }
         else  if (i == tokens.size() - 1)
         {
             std::vector<Token> termTokens = std::vector<Token>(&tokens[lastTermIndex], tokens.data() + tokens.size());
             terms.push_back(new Term(termTokens));
         }
     }
 }
References getParenthesisIndices(), i, Term, and terms.
Referenced by Expression().
Field Documentation
terms
std::vector<Term*> Expression::terms
Definition at line 13 of file expression.hpp.
Referenced by Expression(), getTokens(), Exponential::getTokens(), multiply(), operator==(), organize(), and ~Expression().
The documentation for this class was generated from the following files:
src/expression.hpp
src/expression.cpp