MATH: Fraction Class Reference
Fraction Class Reference
#include <factor.hpp>
Public Member Functions
Fraction ()
Fraction (const std::vector< Token > &tokens)
Fraction (const Fraction &f)
~Fraction ()
Factor * Clone ()
std::vector< Token > getTokens ()
FactorType getType ()
Factor * multiply (Factor *s)
Factor * divide (Factor *s)
bool operator== (Factor *f2)
bool operator!= (Factor *f2)
Factor * multiply (Literal *l)
Factor * multiply (Fraction *f)
Factor * multiply (Parenthesis *f)
Factor * multiply (Exponential *f)
Factor * divide (Literal *l)
Factor * divide (Fraction *f)
Factor * divide (Parenthesis *f)
Factor * divide (Exponential *f)
Public Member Functions inherited from Factor
virtual ~Factor ()=0
Factor (FactorType _type)
Data Fields
Expression * numerator = nullptr
Expression * denominator = nullptr
Data Fields inherited from Factor
FactorType type = FactorType::Invalid
Additional Inherited Members
Public Types inherited from Factor
enum FactorType : char {
FactorType::Literal, FactorType::Exponential, FactorType::Fraction, FactorType::Parenthesis,
FactorType::Invalid
}
Static Public Member Functions inherited from Factor
static Factor * Create (const std::vector< Token > tokens, const FactorType &type)
Detailed Description
Definition at line 79 of file factor.hpp.
Constructor & Destructor Documentation
Fraction() [1/3]
Fraction::Fraction ()
Definition at line 3 of file fraction.cpp.
     : Factor(Factor::FactorType::Fraction) {}
Referenced by Clone(), divide(), and multiply().
Fraction() [2/3]
Fraction::Fraction (const std::vector< Token > & tokens)
Definition at line 6 of file fraction.cpp.
     : Factor(Factor::FactorType::Fraction)
 {
     // find the divider
     long long operatorIndex = -1;
     for (int i = 0; i < tokens.size(); i++)
     {
         if (tokens[i].value == "(")
         {
             i = getParenthesisIndices(tokens, i).second;
         }
         else if (tokens[i].value == "/")
         {
             operatorIndex = i;
             break;
         }
     }
     if (tokens[operatorIndex - 1].value == ")")
         numerator = new Expression(getTokensFromIndices(tokens, std::pair<int,int>(1, operatorIndex - 2)));
     else
         numerator = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(0, operatorIndex - 1)));
     if (tokens[operatorIndex + 1].value == "(")
         denominator = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(operatorIndex + 2, tokens.size() - 2)));
     else
         denominator = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(operatorIndex + 1, tokens.size() - 1)));
 }
References denominator, getParenthesisIndices(), getTokensFromIndices(), i, and numerator.
Fraction() [3/3]
Fraction::Fraction (const Fraction & f)
Definition at line 36 of file fraction.cpp.
     : Factor(Factor::FactorType::Fraction)
 {
     numerator = new Expression(*f.numerator);
     denominator = new Expression(*f.denominator);
 }
References denominator, and numerator.
~Fraction()
Fraction::~Fraction ()
Definition at line 43 of file fraction.cpp.
 {
     delete numerator;
     delete denominator;
 }
References denominator, and numerator.
Member Function Documentation
Clone()
Factor * Fraction::Clone () virtual
Implements Factor.
Definition at line 49 of file fraction.cpp.
 {
     return new Fraction(*this);
 }
References Fraction().
divide() [1/5]
Factor * Fraction::divide (Exponential * f)
Definition at line 170 of file fraction.cpp.
 {
     Fraction* returnFraction = new Fraction(*this);
     returnFraction->denominator->multiply(p);
     return returnFraction;
 }
References denominator, Fraction(), and Expression::multiply().
divide() [2/5]
Factor * Fraction::divide (Factor * s) virtual
Implements Factor.
Definition at line 91 of file fraction.cpp.
 {
     return nullptr;
 }
Referenced by main().
divide() [3/5]
Factor * Fraction::divide (Fraction * f)
Definition at line 149 of file fraction.cpp.
 {
     Fraction* returnFraction = new Fraction(*this);
     returnFraction->numerator->multiply(*f->denominator);
     returnFraction->denominator->multiply(*f->numerator);
     return returnFraction;
 }
References denominator, Fraction(), Expression::multiply(), and numerator.
divide() [4/5]
Factor * Fraction::divide (Literal * l)
Definition at line 139 of file fraction.cpp.
 {
     Fraction* returnFraction = new Fraction(*this);
     returnFraction->denominator->multiply(l);
     return returnFraction;
 }
References denominator, Fraction(), and Expression::multiply().
divide() [5/5]
Factor * Fraction::divide (Parenthesis * f)
Definition at line 160 of file fraction.cpp.
 {
     Fraction* returnFraction = new Fraction(*this);
     returnFraction->denominator->multiply(p);
     return returnFraction;
 }
References denominator, Fraction(), and Expression::multiply().
getTokens()
std::vector< Token > Fraction::getTokens () virtual
Implements Factor.
Definition at line 54 of file fraction.cpp.
 {
     std::vector<Token> returnTokens;
     returnTokens.push_back(Token(Token::TokenType::Operator, "("));
     returnTokens.push_back(Token(Token::TokenType::Operator, "("));
     auto tempTokens = numerator->getTokens();
     returnTokens.insert(returnTokens.end(), tempTokens.begin(), tempTokens.end());
     returnTokens.push_back(Token(Token::TokenType::Operator, ")"));
     returnTokens.push_back(Token(Token::TokenType::Operator, "/"));
     returnTokens.push_back(Token(Token::TokenType::Operator, "("));
     tempTokens = denominator->getTokens();
     returnTokens.insert(returnTokens.end(), tempTokens.begin(), tempTokens.end());
     returnTokens.push_back(Token(Token::TokenType::Operator, ")"));
     returnTokens.push_back(Token(Token::TokenType::Operator, ")"));
     return returnTokens;
 }
References denominator, Expression::getTokens(), numerator, and Token::Operator.
getType()
Factor::FactorType Fraction::getType () virtual
Implements Factor.
Definition at line 81 of file fraction.cpp.
 {
     return type;
 }
References Factor::type.
multiply() [1/5]
Factor * Fraction::multiply (Exponential * f)
Definition at line 134 of file fraction.cpp.
 {
     return nullptr;
 }
multiply() [2/5]
Factor * Fraction::multiply (Factor * s) virtual
Implements Factor.
Definition at line 86 of file fraction.cpp.
 {
     return nullptr;
 }
multiply() [3/5]
Factor * Fraction::multiply (Fraction * f)
Definition at line 118 of file fraction.cpp.
 {
     Fraction* returnFraction = new Fraction(*this);
     returnFraction->numerator->multiply(*f->numerator);
     returnFraction->denominator->multiply(*f->denominator);
     return returnFraction;
 }
References denominator, Fraction(), Expression::multiply(), and numerator.
multiply() [4/5]
Factor * Fraction::multiply (Literal * l)
Definition at line 109 of file fraction.cpp.
 {
     Fraction* returnFraction = new Fraction(*this);
     returnFraction->numerator->multiply(l);
     return returnFraction;
 }
References Fraction(), Expression::multiply(), and numerator.
multiply() [5/5]
Factor * Fraction::multiply (Parenthesis * f)
Definition at line 129 of file fraction.cpp.
 {
     return nullptr;
 }
operator!=()
bool Fraction::operator!= (Factor * f2) virtual
Implements Factor.
Definition at line 104 of file fraction.cpp.
 {
     return false;
 }
operator==()
bool Fraction::operator== (Factor * f2) virtual
Implements Factor.
Definition at line 96 of file fraction.cpp.
 {
     if (f2->type != type)
         return false;
     auto fr2 = dynamic_cast<Fraction*>(f2);
     return (*numerator == *fr2->numerator && *denominator == *fr2->denominator);
 }
References denominator, numerator, and Factor::type.
Field Documentation
denominator
Expression* Fraction::denominator = nullptr
Definition at line 90 of file factor.hpp.
Referenced by divide(), Fraction(), getTokens(), multiply(), operator==(), and ~Fraction().
numerator
Expression* Fraction::numerator = nullptr
Definition at line 89 of file factor.hpp.
Referenced by divide(), Fraction(), getTokens(), multiply(), operator==(), and ~Fraction().
The documentation for this class was generated from the following files:
src/factor.hpp
src/factors/fraction.cpp