MATH: Exponential Class Reference
Exponential Class Reference
#include <factor.hpp>
Public Member Functions
Exponential ()
Exponential (const std::vector< Token > &tokens)
Exponential (const Exponential &e)
~Exponential ()
Factor * Clone ()
std::vector< Token > getTokens ()
FactorType getType ()
Factor * multiply (Factor *s)
Factor * divide (Factor *s)
bool operator== (Factor *f2)
bool operator!= (Factor *f2)
Factor * multiply (Literal *l)
Factor * multiply (Fraction *f)
Factor * multiply (Parenthesis *f)
Factor * multiply (Exponential *f)
Factor * divide (Literal *l)
Factor * divide (Fraction *f)
Factor * divide (Parenthesis *f)
Factor * divide (Exponential *f)
Public Member Functions inherited from Factor
virtual ~Factor ()=0
Factor (FactorType _type)
Data Fields
Expression * base = nullptr
Expression * exponent = nullptr
Data Fields inherited from Factor
FactorType type = FactorType::Invalid
Additional Inherited Members
Public Types inherited from Factor
enum FactorType : char {
FactorType::Literal, FactorType::Exponential, FactorType::Fraction, FactorType::Parenthesis,
FactorType::Invalid
}
Static Public Member Functions inherited from Factor
static Factor * Create (const std::vector< Token > tokens, const FactorType &type)
Detailed Description
Definition at line 152 of file factor.hpp.
Constructor & Destructor Documentation
Exponential() [1/3]
Exponential::Exponential ()
Definition at line 3 of file exponential.cpp.
     : Factor(Factor::FactorType::Exponential) {}
Referenced by Clone().
Exponential() [2/3]
Exponential::Exponential (const std::vector< Token > & tokens)
Definition at line 6 of file exponential.cpp.
     : Factor(Factor::FactorType::Exponential)
 {
     // find the exponent operator
     int operatorIndex = -1;
     for (int i = 0; i < tokens.size(); i++)
     {
         if (tokens[i].value == "(")
         {
             i = getParenthesisIndices(tokens, i).second;
         }
         if (tokens[i].value == "^")
         {
             operatorIndex = i;
             break;
         }
     }
     if (tokens[operatorIndex - 1].value == ")")
         base = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(1, operatorIndex - 2)));
     else
         base = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(0, operatorIndex - 1)));
     if (tokens[operatorIndex + 1].value == "(")
         exponent = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(operatorIndex + 2, tokens.size() - 2)));
     else
         exponent = new Expression(getTokensFromIndices(tokens, std::pair<int, int>(operatorIndex + 1, tokens.size() - 1)));
 }
References base, exponent, getParenthesisIndices(), getTokensFromIndices(), and i.
Exponential() [3/3]
Exponential::Exponential (const Exponential & e)
Definition at line 36 of file exponential.cpp.
     : Factor(Factor::FactorType::Exponential)
 {
     base = new Expression(*e.base);
     exponent = new Expression(*e.exponent);
 }
References base, and exponent.
~Exponential()
Exponential::~Exponential ()
Definition at line 43 of file exponential.cpp.
 {
     delete base;
     delete exponent;
 }
References base, and exponent.
Member Function Documentation
Clone()
Factor * Exponential::Clone () virtual
Implements Factor.
Definition at line 49 of file exponential.cpp.
 {
     return new Exponential(*this);
 }
References Exponential().
divide() [1/5]
Factor* Exponential::divide (Exponential * f)
divide() [2/5]
Factor * Exponential::divide (Factor * s) virtual
Implements Factor.
Definition at line 89 of file exponential.cpp.
 {
     return nullptr;
 }
divide() [3/5]
Factor* Exponential::divide (Fraction * f)
divide() [4/5]
Factor* Exponential::divide (Literal * l)
divide() [5/5]
Factor* Exponential::divide (Parenthesis * f)
getTokens()
std::vector< Token > Exponential::getTokens () virtual
Implements Factor.
Definition at line 54 of file exponential.cpp.
 {
     std::vector<Token> returnVector;
     auto tempTokens = base->getTokens();
     if (base->terms.size() > 1)
         returnVector.push_back(Token(Token::TokenType::Operator, "("));
     returnVector.insert(returnVector.end(), tempTokens.begin(), tempTokens.end());
     if (base->terms.size() > 1)
         returnVector.push_back(Token(Token::TokenType::Operator, ")"));
     returnVector.push_back(Token(Token::TokenType::Operator, "^"));
     tempTokens = exponent->getTokens();
     if (exponent->terms.size() > 1)
         returnVector.push_back(Token(Token::TokenType::Operator, "("));
     returnVector.insert(returnVector.end(), tempTokens.begin(), tempTokens.end());
     if (exponent->terms.size() > 1)
         returnVector.push_back(Token(Token::TokenType::Operator, ")"));
     return returnVector;
 }
References base, exponent, Expression::getTokens(), Token::Operator, and Expression::terms.
getType()
Factor::FactorType Exponential::getType () virtual
Implements Factor.
Definition at line 79 of file exponential.cpp.
 {
     return type;
 }
References Factor::type.
multiply() [1/5]
Factor* Exponential::multiply (Exponential * f)
multiply() [2/5]
Factor * Exponential::multiply (Factor * s) virtual
Implements Factor.
Definition at line 84 of file exponential.cpp.
 {
     return nullptr;
 }
multiply() [3/5]
Factor* Exponential::multiply (Fraction * f)
multiply() [4/5]
Factor* Exponential::multiply (Literal * l)
multiply() [5/5]
Factor* Exponential::multiply (Parenthesis * f)
operator!=()
bool Exponential::operator!= (Factor * f2) virtual
Implements Factor.
Definition at line 99 of file exponential.cpp.
 {
     return false;
 }
operator==()
bool Exponential::operator== (Factor * f2) virtual
Implements Factor.
Definition at line 94 of file exponential.cpp.
 {
     return false;
 }
Field Documentation
base
Expression* Exponential::base = nullptr
Definition at line 162 of file factor.hpp.
Referenced by Exponential(), getTokens(), and ~Exponential().
exponent
Expression* Exponential::exponent = nullptr
Definition at line 163 of file factor.hpp.
Referenced by Exponential(), getTokens(), and ~Exponential().
The documentation for this class was generated from the following files:
src/factor.hpp
src/factors/exponential.cpp