MATH: Parenthesis Class Reference
Parenthesis Class Reference
#include <factor.hpp>
Public Member Functions
Parenthesis ()
Parenthesis (const std::vector< Token > &tokens)
Parenthesis (const Parenthesis &p)
~Parenthesis ()
Factor * Clone ()
std::vector< Token > getTokens ()
FactorType getType ()
Factor * multiply (Factor *s)
Factor * divide (Factor *s)
bool operator== (Factor *f2)
bool operator!= (Factor *f2)
Factor * multiply (Literal *l)
Factor * multiply (Fraction *f)
Factor * multiply (Parenthesis *f)
Factor * multiply (Exponential *f)
Factor * divide (Literal *l)
Factor * divide (Fraction *f)
Factor * divide (Parenthesis *f)
Factor * divide (Exponential *f)
Public Member Functions inherited from Factor
virtual ~Factor ()=0
Factor (FactorType _type)
Data Fields
Expression * expression = nullptr
Data Fields inherited from Factor
FactorType type = FactorType::Invalid
Additional Inherited Members
Public Types inherited from Factor
enum FactorType : char {
FactorType::Literal, FactorType::Exponential, FactorType::Fraction, FactorType::Parenthesis,
FactorType::Invalid
}
Static Public Member Functions inherited from Factor
static Factor * Create (const std::vector< Token > tokens, const FactorType &type)
Detailed Description
Definition at line 117 of file factor.hpp.
Constructor & Destructor Documentation
Parenthesis() [1/3]
Parenthesis::Parenthesis ()
Definition at line 3 of file parenthesis.cpp.
     : Factor(Factor::FactorType::Parenthesis) {}
Referenced by Clone().
Parenthesis() [2/3]
Parenthesis::Parenthesis (const std::vector< Token > & tokens)
Definition at line 6 of file parenthesis.cpp.
     : Factor(Factor::FactorType::Parenthesis)
 {
     expression = new Expression(tokens);
 }
References expression.
Parenthesis() [3/3]
Parenthesis::Parenthesis (const Parenthesis & p)
Definition at line 12 of file parenthesis.cpp.
     : Factor(Factor::FactorType::Parenthesis)
 {
     expression = new Expression(*p.expression);
 }
References expression.
~Parenthesis()
Parenthesis::~Parenthesis ()
Definition at line 18 of file parenthesis.cpp.
 {
     delete expression;
 }
References expression.
Member Function Documentation
Clone()
Factor * Parenthesis::Clone () virtual
Implements Factor.
Definition at line 23 of file parenthesis.cpp.
 {
     return new Parenthesis(*this);
 }
References Parenthesis().
divide() [1/5]
Factor* Parenthesis::divide (Exponential * f)
divide() [2/5]
Factor * Parenthesis::divide (Factor * s) virtual
Implements Factor.
Definition at line 55 of file parenthesis.cpp.
 {
     return nullptr;
 }
divide() [3/5]
Factor* Parenthesis::divide (Fraction * f)
divide() [4/5]
Factor* Parenthesis::divide (Literal * l)
divide() [5/5]
Factor* Parenthesis::divide (Parenthesis * f)
getTokens()
std::vector< Token > Parenthesis::getTokens () virtual
Implements Factor.
Definition at line 28 of file parenthesis.cpp.
 {
     std::vector<Token> returnTokens;
     std::vector<Token> tempTokens;
     returnTokens.push_back(Token(Token::TokenType::Operator, "("));
     tempTokens = expression->getTokens();
     returnTokens.insert(returnTokens.end(), tempTokens.begin(), tempTokens.end());
     returnTokens.push_back(Token(Token::TokenType::Operator, ")"));
     return returnTokens;
 }
References expression, Expression::getTokens(), and Token::Operator.
getType()
Factor::FactorType Parenthesis::getType () virtual
Implements Factor.
Definition at line 45 of file parenthesis.cpp.
 {
     return type;
 }
References Factor::type.
multiply() [1/5]
Factor* Parenthesis::multiply (Exponential * f)
multiply() [2/5]
Factor * Parenthesis::multiply (Factor * s) virtual
Implements Factor.
Definition at line 50 of file parenthesis.cpp.
 {
     return nullptr;
 }
multiply() [3/5]
Factor* Parenthesis::multiply (Fraction * f)
multiply() [4/5]
Factor* Parenthesis::multiply (Literal * l)
multiply() [5/5]
Factor* Parenthesis::multiply (Parenthesis * f)
operator!=()
bool Parenthesis::operator!= (Factor * f2) virtual
Implements Factor.
Definition at line 65 of file parenthesis.cpp.
 {
     return false;
 }
operator==()
bool Parenthesis::operator== (Factor * f2) virtual
Implements Factor.
Definition at line 60 of file parenthesis.cpp.
 {
     return false;
 }
Field Documentation
expression
Expression* Parenthesis::expression = nullptr
Definition at line 127 of file factor.hpp.
Referenced by getTokens(), Parenthesis(), and ~Parenthesis().
The documentation for this class was generated from the following files:
src/factor.hpp
src/factors/parenthesis.cpp