MATH: Term Class Reference
Term Class Reference
#include <term.hpp>
Public Member Functions
Term (const std::vector< Token > &_tokens)
Term (Factor *f)
Term (const Term &t)
~Term ()
std::vector< Token > getTokens ()
bool operator== (const Term &t2)
bool operator!= (const Term &t2)
void combineFactors ()
void multiply (const Term &t)
void multiply (Factor *f)
Data Fields
std::vector< Factor * > factors
bool sign = true
Detailed Description
Definition at line 5 of file term.hpp.
Constructor & Destructor Documentation
Term() [1/3]
Term::Term (const std::vector< Token > & _tokens)
Definition at line 3 of file term.cpp.
 {
     auto tokens = _tokens;
     if (tokens[0].value == "-")
     {
         sign = false;
         tokens.erase(tokens.begin());
     }
     else if (tokens[0].value == "+")
     {
         sign = true;
         tokens.erase(tokens.begin());
     }
     else sign = true;
     // check from left to right
     int lastCutOff = 0;
     Factor::FactorType currentType = Factor::FactorType::Literal;
     for (int i = 0; i < tokens.size(); i++)
     {
         // if we encounter a token that is part of literal
         if ((tokens[i].type == Token::TokenType::Identifier || tokens[i].type == Token::TokenType::Literal || tokens[i].value == "*") || (tokens[i].value == "^" && tokens[i + 1].type == Token::TokenType::Literal))
         {
             currentType = Factor::FactorType::Literal;
             // if this is the last token
             if (i == tokens.size() - 1)
             {
                 auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                 factors.push_back(Factor::Create(factorTokens, currentType));
             }
         }
         else
         {
             if (i != 0 && currentType == Factor::FactorType::Literal && tokens[i].value != "^" && tokens[i].value != "/")
             {
                 auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i - 1));
                 factors.push_back(Factor::Create(factorTokens, currentType));
             }
             if (tokens[i].value == "^")
             {
                 if (i > 1)
                 {
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i - 2));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                     lastCutOff = i - 1;
                 }
                 currentType = Factor::FactorType::Exponential;
                 if (tokens[i + 1].value == "(")
                 {
                     i = getParenthesisIndices(tokens, i).second;
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                 }
                 else
                 {
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i + 1));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                     i++;
                 }
             }
             else if (tokens[i].value == "/")
             {
                 if (i > 1)
                 {
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i - 2));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                     lastCutOff = i - 1;
                 }
                 lastCutOff = i - 1;
                 currentType = Factor::FactorType::Fraction;
                 if (tokens[i + 1].value == "(")
                 {
                     i = getParenthesisIndices(tokens, i).second;
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                 }
                 else
                 {
                     i++;
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                     lastCutOff = i + 1;
                 }
             }
             else if (tokens[i].value == "(")
             {
                 lastCutOff = i;
                 currentType = Factor::FactorType::Parenthesis;
                 i = getParenthesisIndices(tokens, i).second + 1;
                 if (i >= tokens.size() - 1)
                 {
                     // type is parenthesis
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff + 1, i - 2));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                 }
                 else if (tokens[i].value == "^")
                 {
                     currentType = Factor::FactorType::Exponential;
                     if (tokens[i + 1].value == "(")
                     {
                         i = getParenthesisIndices(tokens, i).second;
                         auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                         factors.push_back(Factor::Create(factorTokens, currentType));
                     }
                     else
                     {
                         i++;
                         auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                         factors.push_back(Factor::Create(factorTokens, currentType));
                     }
                 }
                 else if (tokens[i].value == "/")
                 {
                     currentType = Factor::FactorType::Fraction;
                     if (tokens[i + 1].value == "(")
                     {
                         i = getParenthesisIndices(tokens, i).second;
                         auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                         factors.push_back(Factor::Create(factorTokens, currentType));
                     }
                     else
                     {
                         i++;
                         auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff, i));
                         factors.push_back(Factor::Create(factorTokens, currentType));
                     }
                 }
                 else
                 {
                     // type is parenthesis
                     auto factorTokens = getTokensFromIndices(tokens, std::pair<int, int>(lastCutOff + 1, i - 1));
                     factors.push_back(Factor::Create(factorTokens, currentType));
                 }
             }
             lastCutOff = 1 + i;
         }
     }
 }
References Factor::Create(), Factor::Exponential, factors, Factor::Fraction, getParenthesisIndices(), getTokensFromIndices(), i, Token::Identifier, Factor::Literal, Token::Literal, Factor::Parenthesis, and sign.
Term() [2/3]
Term::Term (Factor * f)
Definition at line 148 of file term.cpp.
 {
     factors.push_back(f);
 }
References factors.
Term() [3/3]
Term::Term (const Term & t)
Definition at line 153 of file term.cpp.
 {
     sign = t.sign;
     for (auto factor : t.factors)
     {
         factors.push_back(factor->Clone());
     }
 }
References factors, and sign.
~Term()
Term::~Term ()
Definition at line 162 of file term.cpp.
 {
     for (auto factor : factors)
         delete factor;
 }
References factors.
Member Function Documentation
combineFactors()
void Term::combineFactors ()
Definition at line 213 of file term.cpp.
 {
     for (int i = 0; i < factors.size(); i++)
     {
         for (int j = i + 1; j < factors.size(); j++)
         {
             if (factors[j]->type == factors[i]->type && factors[i]->type == Factor::FactorType::Literal)
             {
                 auto temp = factors[i];
                 factors[i] = factors[i]->multiply(factors[j]);
                 delete temp;
                 delete factors[j];
                 factors.erase(factors.begin() + j);
             }
         }
     }
 }
References factors, i, and Factor::Literal.
Referenced by multiply().
getTokens()
std::vector< Token > Term::getTokens ()
Definition at line 168 of file term.cpp.
 {
     std::vector<Token> returnTokens;
     if (sign)
         returnTokens.push_back(Token(Token::TokenType::Operator, "+"));
     else
         returnTokens.push_back(Token(Token::TokenType::Operator, "-"));
     for (int i = 0; i < factors.size(); i++)
     {
         std::vector<Token> tempTokens = factors[i]->getTokens();
         returnTokens.insert(returnTokens.end(), tempTokens.begin(), tempTokens.end());
         if (i != factors.size() - 1)
             returnTokens.push_back(Token(Token::TokenType::Operator, "*"));
     }
     return returnTokens;
 }
References factors, i, Token::Operator, and sign.
multiply() [1/2]
void Term::multiply (const Term & t)
Definition at line 231 of file term.cpp.
 {
     for (auto factor : t.factors)
     {
         factors.push_back(factor->Clone());
     }
     combineFactors();
 }
References combineFactors(), and factors.
Referenced by Expression::multiply().
multiply() [2/2]
void Term::multiply (Factor * f)
Definition at line 240 of file term.cpp.
 {
     bool hasMultiplied = false;
     for (auto& factor : factors)
     {
         auto multiplied = factor->multiply(f);
         if (multiplied != nullptr)
         {
             auto temp = factor;
             factor = multiplied;
             delete temp;
             hasMultiplied = true;
             break;
         }
     }
     if (!hasMultiplied)
     {
         factors.push_back(f);
     }
 }
References factors.
operator!=()
bool Term::operator!= (const Term & t2)
Definition at line 208 of file term.cpp.
 {
     return !(*this == t2);
 }
operator==()
bool Term::operator== (const Term & t2)
Definition at line 187 of file term.cpp.
 {
     if (factors.size() != t2.factors.size() || sign != t2.sign)
         return false;
     // even if the factors are out of order, they still evaluate to the same. Therefore we need to make sure that each factor in one term is also existant in the other.
     for (int i = 0; i < factors.size(); i++)
     {
         bool exists = false;
         for (int j = 0; j < factors.size(); j++)
         {
             if (*t2.factors[i] == factors[j])
                 exists = true;
         }
         if (!exists)
             return false;
     }
     return true;
 }
References factors, i, and sign.
Field Documentation
factors
std::vector<Factor*> Term::factors
Definition at line 13 of file term.hpp.
Referenced by combineFactors(), getTokens(), multiply(), operator==(), Term(), and ~Term().
sign
bool Term::sign = true
Definition at line 15 of file term.hpp.
Referenced by getTokens(), operator==(), and Term().
The documentation for this class was generated from the following files:
src/term.hpp
src/term.cpp