MATH: Literal Class Reference
Literal Class Reference
#include <factor.hpp>
Public Member Functions
Literal ()
Literal (const Literal &l)
Literal (const std::vector< Token > &_tokens)
Factor * Clone ()
std::vector< Token > getTokens ()
FactorType getType ()
Factor * multiply (Factor *s)
Factor * divide (Factor *s)
bool operator== (Factor *f2)
bool operator!= (Factor *f2)
Factor * multiply (Literal *l)
Factor * multiply (Fraction *f)
Factor * multiply (Parenthesis *p)
Factor * multiply (Exponential *p)
Factor * divide (Literal *l)
Public Member Functions inherited from Factor
virtual ~Factor ()=0
Factor (FactorType _type)
Private Attributes
double value = 1
std::vector< std::pair< std::string, double > > identifiers
Additional Inherited Members
Public Types inherited from Factor
enum FactorType : char {
FactorType::Literal, FactorType::Exponential, FactorType::Fraction, FactorType::Parenthesis,
FactorType::Invalid
}
Static Public Member Functions inherited from Factor
static Factor * Create (const std::vector< Token > tokens, const FactorType &type)
Data Fields inherited from Factor
FactorType type = FactorType::Invalid
Detailed Description
Definition at line 43 of file factor.hpp.
Constructor & Destructor Documentation
Literal() [1/3]
Literal::Literal ()
Definition at line 4 of file literal.cpp.
     : Factor(Factor::FactorType::Literal) {}
Referenced by Clone(), divide(), and multiply().
Literal() [2/3]
Literal::Literal (const Literal & l)
Definition at line 7 of file literal.cpp.
     : Factor(FactorType::Literal)
 {
     value = l.value;
     identifiers = l.identifiers;
 }
References identifiers, and value.
Literal() [3/3]
Literal::Literal (const std::vector< Token > & _tokens)
Definition at line 14 of file literal.cpp.
     : Factor(FactorType::Literal)
 {
     for (int i = 0; i < tokens.size(); i++)
     {
         if (tokens[i].type == Token::TokenType::Literal)
         {
                 if (i < tokens.size() - 1 && tokens[i + 1].value == "^")
                 {
                     value *= std::pow(std::stod(tokens[i].value), std::stod(tokens[i + 2].value));
                     i += 2;
                 }
                 else
                     value *= std::stod(tokens[i].value);
         }
         else if (tokens[i].type == Token::TokenType::Identifier)
         {
             // get exponent, if any
             bool isExponent = false;
             double exponent = 1;
             if (i < tokens.size() - 1)
             {
                 // if the next token is a ^ we give it the literal next to it. Else, the exponent is just 1
                 if (tokens[i + 1].value == "^")
                 {
                     exponent = std::stod(tokens[i + 2].value);
                     isExponent = true;
                 }
             }
             // check if identifier already exists
             bool exists = false;
             for (auto& identifier : identifiers)
             {
                 if (identifier.first == tokens[i].value)
                 {
                     identifier.second += exponent;
                     exists = true;
                     break;
                 }
             }
             if (!exists)
                 identifiers.push_back(std::pair<std::string, double>(tokens[i].value, exponent));
             if (isExponent)
                 i += 2;
         }
     }
 }
References i, Token::Identifier, identifiers, Token::Literal, Factor::type, and value.
Member Function Documentation
Clone()
Factor * Literal::Clone () virtual
Implements Factor.
Definition at line 64 of file literal.cpp.
 {
     return new Literal(*this);
 }
References Literal().
divide() [1/2]
Factor * Literal::divide (Factor * s) virtual
Implements Factor.
Definition at line 134 of file literal.cpp.
 {
     return nullptr;
 }
divide() [2/2]
Factor * Literal::divide (Literal * l)
Definition at line 212 of file literal.cpp.
 {
     // if the two literals are the same, we return a 1
     if (*this == l)
     {
         return new Literal(std::vector<Token>({ Token(Token::TokenType::Literal, "1") }));
     }
     auto numLiteral = new Literal(*this);
     auto denLiteral = new Literal(*l);
     numLiteral->value /= denLiteral->value;
     denLiteral->value = 1;
     for (int i = 0; i < denLiteral->identifiers.size(); i++)
     {
         for (int j = 0; j < numLiteral->identifiers.size(); j++)
         {
             if (denLiteral->identifiers[i].first == numLiteral->identifiers[j].first)
             {
                 // if the divisors identifier is raised to a higher power
                 if (denLiteral->identifiers[i].second > numLiteral->identifiers[j].second)
                 {
                     denLiteral->identifiers[i].second -= numLiteral->identifiers[j].second;
                     numLiteral->identifiers.erase(numLiteral->identifiers.begin() + j);
                 }
                 else if (denLiteral->identifiers[i].second == numLiteral->identifiers[j].second)
                 {
                     numLiteral->identifiers.erase(numLiteral->identifiers.begin() + j);
                     denLiteral->identifiers.erase(denLiteral->identifiers.begin() + i);
                 }
                 else
                 {
                     numLiteral->identifiers[j].second -= denLiteral->identifiers[i].second;
                     denLiteral->identifiers.erase(denLiteral->identifiers.begin() + i);
                 }
             }
         }
     }
     if (denLiteral->identifiers.size() == 0)
         return numLiteral;
     else
     {
         auto returnFraction = new Fraction();
         returnFraction->numerator = new Expression(numLiteral);
         returnFraction->denominator = new Expression(denLiteral);
         return returnFraction;
     }
 }
References i, Literal(), and Token::Literal.
getTokens()
std::vector< Token > Literal::getTokens () virtual
Implements Factor.
Definition at line 69 of file literal.cpp.
 {
     std::vector<Token> returnTokens;
     if (value != 1 || identifiers.size() == 0)
         returnTokens.push_back(Token(Token::TokenType::Literal, std::to_string(value)));
     for (auto identifier : identifiers)
     {
         if (value != 1)
             returnTokens.push_back(Token(Token::TokenType::Operator, "*"));
         if (identifier.second == 1)
         {
             returnTokens.push_back(Token(Token::TokenType::Identifier, identifier.first));
         }
         else
         {
             std::vector<Token> tempTokens;
             tempTokens.push_back( Token(Token::TokenType::Identifier, identifier.first));
             tempTokens.push_back(Token(Token::TokenType::Operator, "^"));
             tempTokens.push_back(Token(Token::TokenType::Literal, std::to_string(identifier.second)));
             returnTokens.insert(returnTokens.end(), tempTokens.begin(), tempTokens.end());
         }
     }
     return returnTokens;
 }
References Token::Identifier, identifiers, Token::Literal, Token::Operator, and value.
getType()
Factor::FactorType Literal::getType () virtual
Implements Factor.
Definition at line 99 of file literal.cpp.
 {
     return type;
 }
References Factor::type.
multiply() [1/5]
Factor * Literal::multiply (Exponential * p)
Definition at line 207 of file literal.cpp.
 {
     return nullptr;
 }
multiply() [2/5]
Factor * Literal::multiply (Factor * s) virtual
Implements Factor.
Definition at line 104 of file literal.cpp.
 {
     switch (s->type)
     {
     case FactorType::Literal:
     {
         Literal* l = dynamic_cast<Literal*>(s);
         return multiply(l);
     }
     case FactorType::Fraction:
     {
         Fraction* l = dynamic_cast<Fraction*>(s);
         return multiply(l);
     }
     case FactorType::Parenthesis:
     {
         Parenthesis* l = dynamic_cast<Parenthesis*>(s);
         return multiply(l);
     }
     case FactorType::Exponential:
     {
         Exponential* l = dynamic_cast<Exponential*>(s);
         return multiply(l);
     }
     default:
         break;
     }
     return nullptr;
 }
References Factor::Exponential, Factor::Fraction, Factor::Literal, Factor::Parenthesis, and Factor::type.
multiply() [3/5]
Factor * Literal::multiply (Fraction * f)
Definition at line 191 of file literal.cpp.
 {
     auto returnFraction = new Fraction(*f);
     returnFraction->numerator->multiply(this);
     return returnFraction;
 }
multiply() [4/5]
Factor * Literal::multiply (Literal * l)
Definition at line 155 of file literal.cpp.
 {
     Literal* returnFactor = new Literal(*this);
     returnFactor->value *= l->value;
     // loop through identifiers of the multiplier
     for (int i = 0; i < l->identifiers.size(); i++)
     {
         // if identifier is already in our vector
         int identIndex = -1;
         // looping through identifiers of this factor
         for (int j = 0; j < returnFactor->identifiers.size(); j++)
         {
             // if the identifier name is the same as the one from multiplier
             if (l->identifiers[i].first == returnFactor->identifiers[j].first)
             {
                 // we set the index
                 identIndex = j;
                 break;
             }
         }
         // if we have set the index
         if (identIndex != -1)
         {
             // the exponents are added together
             returnFactor->identifiers[identIndex].second += l->identifiers[i].second;
         }
         else
         {
             // the identifier is pushed back, if it isn't found.
             returnFactor->identifiers.push_back(l->identifiers[i]);
         }
     }
     return returnFactor;
 }
References i, identifiers, Literal(), and value.
multiply() [5/5]
Factor * Literal::multiply (Parenthesis * p)
Definition at line 199 of file literal.cpp.
 {
     auto returnParenthesis = new Parenthesis(*p);
     returnParenthesis->expression->multiply(this);
     return returnParenthesis;
 }
operator!=()
bool Literal::operator!= (Factor * f2) virtual
Implements Factor.
Definition at line 150 of file literal.cpp.
 {
     return !(*this == f2);
 }
operator==()
bool Literal::operator== (Factor * f2) virtual
Implements Factor.
Definition at line 139 of file literal.cpp.
 {
     if (type != f2->type)
         return false;
     else
     {
         Literal* l2 = dynamic_cast<Literal*>(f2);
         return (identifiers == l2->identifiers && value == l2->value);
     }
 }
References identifiers, Factor::type, and value.
Field Documentation
identifiers
std::vector<std::pair<std::string, double> > Literal::identifiers private
Definition at line 55 of file factor.hpp.
Referenced by getTokens(), Literal(), multiply(), and operator==().
value
double Literal::value = 1 private
Definition at line 53 of file factor.hpp.
Referenced by getTokens(), Literal(), multiply(), and operator==().
The documentation for this class was generated from the following files:
src/factor.hpp
src/factors/literal.cpp