MATH: src/token.cpp File Reference
token.cpp File Reference
#include "token.hpp"
#include <iostream>
Functions
std::vector< Token > lexify (std::string input)
std::ostream & operator<< (std::ostream &os, const Token &t)
bool operator== (const Token &t1, const Token &t2)
Token::TokenType getTypeFromChar (char c)
std::pair< int, int > getParenthesisIndices (std::vector< Token > tokens, int offset)
std::vector< Token > getTokensFromIndices (const std::vector< Token > &tokens, std::pair< int, int > indices)
std::string getStringFromTokens (const std::vector< Token > &tokens)
Function Documentation
getParenthesisIndices()
std::pair<int, int> getParenthesisIndices (std::vector< Token > tokens, int offset)
Definition at line 134 of file token.cpp.
 {
     size_t numLeftParentheses = 0, numRightParentheses = 0;
     size_t leftParenthesisIndex, rightParenthesisIndex;
     // looping though the tokens
     for (size_t i = offset; i < tokens.size(); i++)
     {
         // if we encounter a left parenthesis
         if (tokens[i].type == Token::TokenType::Operator && tokens[i].value == "(")
         {
             // update index and number of opening parentheses
             leftParenthesisIndex = i;
             numLeftParentheses++;
             for (size_t j = i + 1; j < tokens.size(); j++)
             {
                 // if we find more left parentheses, add to the count, and the same with right ones
                 if (tokens[j].type == Token::TokenType::Operator && tokens[j].value == "(")
                     numLeftParentheses++;
                 else if (tokens[j].type == Token::TokenType::Operator && tokens[j].value == ")")
                     numRightParentheses++;
                 // once there is the same amount of each, the first we found must have been closed.
                 if (numLeftParentheses == numRightParentheses)
                 {
                     rightParenthesisIndex = j;
                     return std::pair<int, int>(leftParenthesisIndex, rightParenthesisIndex);
                 }
             }
         }
     }
     return std::pair<int, int>(-1, -1);
 }
References i, and Token::Operator.
Referenced by Exponential::Exponential(), Fraction::Fraction(), Expression::organize(), and Term::Term().
getStringFromTokens()
std::string getStringFromTokens (const std::vector< Token > & tokens)
Definition at line 173 of file token.cpp.
 {
     std::string returnString = "";
     for (auto token : tokens)
     {
         returnString += token.value;
     }
     return returnString;
 }
Referenced by main().
getTokensFromIndices()
std::vector<Token> getTokensFromIndices (const std::vector< Token > & tokens, std::pair< int, int > indices)
Definition at line 168 of file token.cpp.
 {
     return std::vector<Token>(&tokens[indices.first], &tokens[indices.second] + 1);
 }
Referenced by Exponential::Exponential(), Fraction::Fraction(), and Term::Term().
getTypeFromChar()
Token::TokenType getTypeFromChar (char c)
Definition at line 120 of file token.cpp.
 {
     if (arrayContains(Global::operators, c))
         return Token::TokenType::Operator;
     else if ((c >= 48 && c <= 57) || c == '.')
         return Token::TokenType::Literal;
     else if ((c >= 65 && c <= 90) || (c >= 97 && c <= 122) || c == 95)
         return Token::TokenType::Identifier;
     else if (arrayContains(Global::seperators, c))
         return Token::TokenType::Seperator;
     else
         return Token::TokenType::Invalid;
 }
References arrayContains(), Token::Identifier, Token::Invalid, Token::Literal, Token::Operator, Global::operators, Token::Seperator, and Global::seperators.
lexify()
std::vector<Token> lexify (std::string input)
Definition at line 33 of file token.cpp.
 {
     std::vector<Token> tokens;
     input.erase(std::remove(input.begin(), input.end(), ' '), input.end());
     Token currentToken;
     char currentChar;
     Token::TokenType currentType = Token::TokenType::Invalid, prevType;
     std::string buffer;
     bool hasADecimal = false;
     currentChar = input[0];
     prevType = getTypeFromChar(currentChar);
     buffer = currentChar;
     for (size_t i = 1; i < input.size(); i++)
     {
         currentChar = input[i];
         currentType = getTypeFromChar(currentChar);
         if (prevType == Token::TokenType::Operator)
         {
             currentToken.type = prevType;
             currentToken.value = buffer;
             buffer = currentChar;
             prevType = currentType;
             tokens.push_back(currentToken);
         }
         else if ((currentType == Token::TokenType::Literal && prevType == Token::TokenType::Literal) || (prevType == Token::TokenType::Literal && currentChar == '.' && !hasADecimal))
         {
             if (currentChar == '.')
                 hasADecimal = true;
             buffer += currentChar;
         }
         else if (prevType == Token::TokenType::Identifier && (currentType == Token::TokenType::Identifier || currentType == Token::TokenType::Literal))
         {
             buffer += currentChar;
         }
         else if (currentType != prevType)
         {
             /*if (mapContainsKey(storedFunctions, buffer))
             {
                 prevType = Token::TokenType::Function;
             }*/
             hasADecimal = false;
             currentToken.type = prevType;
             currentToken.value = buffer;
             tokens.push_back(currentToken);
             buffer = currentChar;
             prevType = currentType;
         }
         else if (currentType == Token::TokenType::Invalid)
         {
             std::cout << "Invalid character in expression at character " + i + 1 << std::endl;
             return std::vector<Token>();
         }
     }
     if (input.size() == 1)
     {
         currentToken.type = prevType;
         currentToken.value = buffer;
         tokens.push_back(currentToken);
     }
     else
     {
         currentToken.type = currentType;
         currentToken.value = buffer;
         tokens.push_back(currentToken);
     }
     return tokens;
 }
References Token::TokenTypeString(), and Token::value.
Referenced by main().
operator<<()
std::ostream& operator<< (std::ostream & os, const Token & t)
Definition at line 109 of file token.cpp.
 {
     os << t.printString();
     return os;
 }
References Token::printString().
operator==()
bool operator== (const Token & t1, const Token & t2)
Definition at line 115 of file token.cpp.
 {
     return (t1.type == t2.type && t1.value == t2.value);
 }
References Token::type, and Token::value.